server:
  port: 9092
  shutdown: graceful
  netty:
    # время ожидания установки TCP соединения с сервером
    connection-timeout: 3s
    # время ожидания до закрытия TCP соединения, по которому не передаются данные
    idle-timeout: 20s

spring:
  application:
    name: orders-service
  lifecycle:
    timeout-per-shutdown-phase: 30s
  r2dbc:
    username: user
    password: password
    url: r2dbc:postgresql://localhost:15432/orders_service_db
    pool:
      max-create-connection-time: 2s
      initial-size: 6
      max-size: 12
  flyway:
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    url: jdbc:postgresql://localhost:15432/orders_service_db

external:
  menu-service-url: http://localhost:9091
  menu-info-path: /v1/menu-item/menu-info
  default-timeout: 2s
  retry-backoff: 100ms
  retry-count: 5
  retry-jitter: 0.75